version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "6002:6002"
    environment:
      - DATABASE_URL=postgresql://postgres_0clu_user:wfgIIyZqkUlBWAgDm6AsRZZvdURQrh81@dpg-cvkl5aogjchc73ce2lvg-a/postgres_0clu
      - PORT=6002
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
