# Step 1: Build Stage
FROM node:18 AS build

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY backend/ ./


# Step 2: Production Stage
FROM node:18-slim

# Set the working directory in the container
WORKDIR /app

# Copy the built application from the build stage
COPY --from=build /app ./

# Expose the port your backend runs on
EXPOSE 6002

# Run the Express app
CMD ["npm", "start"]
